// <auto-generated />
using System;
using AMGAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AMGAPI.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20221014003656_initdb")]
    partial class initdb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AMGAPI.Data.Canbo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Anhdaidien_ten")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Anhdaidien_url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CapbacId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChucvuId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Dienthoai_cd1")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Dienthoai_cd2")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Dienthoai_cd3")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Dienthoai_mobile")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<Guid>("DonviId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Matkhau")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("Ngaysinh")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Publickey_status")
                        .HasColumnType("bit");

                    b.Property<string>("Publickey_value")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Tendangnhap")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Tendaydu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CapbacId");

                    b.HasIndex("ChucvuId");

                    b.HasIndex("DonviId");

                    b.HasIndex("RoleId");

                    b.HasIndex("Tendangnhap")
                        .IsUnique();

                    b.ToTable("Canbo");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fe3cad63-5187-4f4b-adaa-798ff932b5c4"),
                            CapbacId = new Guid("3f7eb3c4-28b0-48f4-bda4-08da44746177"),
                            ChucvuId = new Guid("3509de02-52dd-4ba7-e244-08da44747730"),
                            Dienthoai_mobile = "0123456789",
                            DonviId = new Guid("07ca1673-4e6c-448e-8f65-a1ef3b65717b"),
                            Matkhau = "1",
                            Publickey_status = false,
                            RoleId = new Guid("830da2e4-c293-4026-b2e6-29ad8c935def"),
                            Status = false,
                            Tendangnhap = "admin",
                            Tendaydu = "Admin"
                        });
                });

            modelBuilder.Entity("AMGAPI.Data.Dangkykenh", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CanboDangkyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ID_Canbodangky")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IP_Ungdung")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("IdDonvi")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Log_process")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Ngayduyet")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Ngaysua")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<DateTime>("Ngaytao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<int>("Port_Ungdung")
                        .HasColumnType("int");

                    b.Property<string>("TenNguoidangky")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenUngdung")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Trangthai")
                        .HasColumnType("int");

                    b.Property<Guid>("UngdungId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("is_Delete")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CanboDangkyId");

                    b.HasIndex("UngdungId");

                    b.ToTable("Dangkykenh");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e0f582de-420f-4902-8cee-cf85389cc6bf"),
                            ID_Canbodangky = new Guid("fe3cad63-5187-4f4b-adaa-798ff932b5c4"),
                            IP_Ungdung = "10.10.10.1",
                            IdDonvi = new Guid("574b452c-b586-499b-d7b9-08da44749b96"),
                            Ngayduyet = new DateTime(2022, 10, 14, 0, 36, 56, 149, DateTimeKind.Utc).AddTicks(4572),
                            Ngaysua = new DateTime(2022, 10, 14, 0, 36, 56, 149, DateTimeKind.Utc).AddTicks(4147),
                            Ngaytao = new DateTime(2022, 10, 14, 0, 36, 56, 149, DateTimeKind.Utc).AddTicks(3907),
                            Port_Ungdung = 80,
                            TenNguoidangky = "Đc Vân",
                            TenUngdung = "CĐ-ĐH",
                            Trangthai = 0,
                            UngdungId = new Guid("5f606928-41d0-4b2d-a251-56ed76e1dffd"),
                            is_Delete = false
                        },
                        new
                        {
                            Id = new Guid("37f70f55-7dcb-4ca5-b0c8-7466b9cedf3d"),
                            ID_Canbodangky = new Guid("fe3cad63-5187-4f4b-adaa-798ff932b5c4"),
                            IP_Ungdung = "10.10.10.2",
                            IdDonvi = new Guid("574b452c-b586-499b-d7b9-08da44749b96"),
                            Ngayduyet = new DateTime(2022, 10, 14, 0, 36, 56, 149, DateTimeKind.Utc).AddTicks(5132),
                            Ngaysua = new DateTime(2022, 10, 14, 0, 36, 56, 149, DateTimeKind.Utc).AddTicks(5131),
                            Ngaytao = new DateTime(2022, 10, 14, 0, 36, 56, 149, DateTimeKind.Utc).AddTicks(5129),
                            Port_Ungdung = 80,
                            TenNguoidangky = "Đc Minh",
                            TenUngdung = "CĐN",
                            Trangthai = 0,
                            UngdungId = new Guid("16a5a7df-3f2c-49d9-b5ee-024e2487d7e1"),
                            is_Delete = false
                        });
                });

            modelBuilder.Entity("AMGAPI.Data.Dangkykenh_Duyet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Canbothamdinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DangkykenhId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ID_Canboduyet")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IP_Internalgate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("IdDonvi")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Log_process")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<DateTime>("Ngaysua")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<int>("Port_Internalgate")
                        .HasColumnType("int");

                    b.Property<string>("TenUngdung")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Trangthai")
                        .HasColumnType("bit");

                    b.Property<Guid>("UngdungId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("is_Delete")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DangkykenhId");

                    b.HasIndex("ID_Canboduyet");

                    b.HasIndex("UngdungId");

                    b.ToTable("Dangkykenh_Duyet");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6746de28-4d95-4a77-96de-c75a8eb80bc4"),
                            Canbothamdinh = "Đồng chí A",
                            DangkykenhId = new Guid("e0f582de-420f-4902-8cee-cf85389cc6bf"),
                            ID_Canboduyet = new Guid("fe3cad63-5187-4f4b-adaa-798ff932b5c4"),
                            IP_Internalgate = "10.10.10.0",
                            IdDonvi = new Guid("574b452c-b586-499b-d7b9-08da44749b96"),
                            NgayTao = new DateTime(2022, 10, 14, 0, 36, 56, 149, DateTimeKind.Utc).AddTicks(7496),
                            Ngaysua = new DateTime(2022, 10, 14, 0, 36, 56, 149, DateTimeKind.Utc).AddTicks(7778),
                            Port_Internalgate = 80,
                            TenUngdung = "CĐ-ĐH",
                            Trangthai = false,
                            UngdungId = new Guid("5f606928-41d0-4b2d-a251-56ed76e1dffd"),
                            is_Delete = false
                        },
                        new
                        {
                            Id = new Guid("97c3636d-cff0-4b80-b426-dc299e373053"),
                            Canbothamdinh = "Đồng chí A",
                            DangkykenhId = new Guid("e0f582de-420f-4902-8cee-cf85389cc6bf"),
                            ID_Canboduyet = new Guid("fe3cad63-5187-4f4b-adaa-798ff932b5c4"),
                            IP_Internalgate = "10.10.10.0",
                            IdDonvi = new Guid("574b452c-b586-499b-d7b9-08da44749b96"),
                            NgayTao = new DateTime(2022, 10, 14, 0, 36, 56, 149, DateTimeKind.Utc).AddTicks(8485),
                            Ngaysua = new DateTime(2022, 10, 14, 0, 36, 56, 149, DateTimeKind.Utc).AddTicks(8487),
                            Port_Internalgate = 80,
                            TenUngdung = "CĐN",
                            Trangthai = false,
                            UngdungId = new Guid("16a5a7df-3f2c-49d9-b5ee-024e2487d7e1"),
                            is_Delete = false
                        });
                });

            modelBuilder.Entity("AMGAPI.Data.Danhsachnguoidung", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CanboId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdDonvi")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Ngaysua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Ngaytao")
                        .HasColumnType("datetime2");

                    b.Property<bool>("NhanSMS")
                        .HasColumnType("bit");

                    b.Property<string>("Public_Key")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sodienthoai")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<Guid>("SokenhId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Trangthai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CanboId");

                    b.HasIndex("SokenhId");

                    b.ToTable("Danhsachnguoidung");
                });

            modelBuilder.Entity("AMGAPI.Data.DmApp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ghichu")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Viettat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("is_Delete")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("DmApp");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e680169e-7c1c-4be3-8158-4146ddc1c587"),
                            Ghichu = "Quản trị danh mục",
                            Ten = "Quản trị danh mục",
                            Viettat = "QLDM",
                            is_Delete = false
                        },
                        new
                        {
                            Id = new Guid("c00464fc-ea88-428b-8904-25fa4afc07d5"),
                            Ghichu = "Đăng ký kênh",
                            Ten = "Quản lý kênh",
                            Viettat = "QLKenh",
                            is_Delete = false
                        },
                        new
                        {
                            Id = new Guid("3efbe184-cf3b-4afc-936c-bdf5f3784615"),
                            Ghichu = "Hệ thống",
                            Ten = "Hệ thống",
                            Viettat = "Hệ thống",
                            is_Delete = false
                        });
                });

            modelBuilder.Entity("AMGAPI.Data.DmBlackWord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Ngaysua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Ngaytao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("DmBlackWord");
                });

            modelBuilder.Entity("AMGAPI.Data.DmCapbac", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ghichu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Viettat")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("DmCapbac");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3f7eb3c4-28b0-48f4-bda4-08da44746177"),
                            Ghichu = "4/",
                            Status = true,
                            Ten = "Đại úy",
                            Viettat = "4/"
                        },
                        new
                        {
                            Id = new Guid("df803dd4-2fac-49a3-5c0c-08da49246d39"),
                            Ghichu = "3/",
                            Status = true,
                            Ten = "Thượng úy",
                            Viettat = "3/"
                        },
                        new
                        {
                            Id = new Guid("fe3cad63-5187-4f4b-adaa-798ff932b5c4"),
                            Ghichu = "1/",
                            Status = true,
                            Ten = "Thiếu úy",
                            Viettat = "1/"
                        });
                });

            modelBuilder.Entity("AMGAPI.Data.DmChucvu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ghichu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Viettat")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("DmChucvu");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3509de02-52dd-4ba7-e244-08da44747730"),
                            Ghichu = "TP",
                            Status = true,
                            Ten = "Trưởng phòng",
                            Viettat = "TP"
                        },
                        new
                        {
                            Id = new Guid("68cf890a-33e7-496a-c46e-08da4475ee1a"),
                            Ghichu = "PTP",
                            Status = true,
                            Ten = "Phó Trưởng phòng",
                            Viettat = "PTP"
                        });
                });

            modelBuilder.Entity("AMGAPI.Data.DmDonvi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DangkykenhId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("Dangkykenh_duyetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ghichu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ma")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SoquanlykenhId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Viettat")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("DangkykenhId");

                    b.HasIndex("Dangkykenh_duyetId");

                    b.HasIndex("SoquanlykenhId");

                    b.ToTable("DmDonvi");

                    b.HasData(
                        new
                        {
                            Id = new Guid("574b452c-b586-499b-d7b9-08da44749b96"),
                            Ghichu = "Viện 10",
                            Ma = "V10",
                            Status = true,
                            Ten = "Viện 10",
                            Viettat = "V10"
                        },
                        new
                        {
                            Id = new Guid("07ca1673-4e6c-448e-8f65-a1ef3b65717b"),
                            Ghichu = "PKH",
                            Ma = "PKH",
                            ParentId = new Guid("574b452c-b586-499b-d7b9-08da44749b96"),
                            Status = true,
                            Ten = "PKH",
                            Viettat = "PKH"
                        });
                });

            modelBuilder.Entity("AMGAPI.Data.DmFeature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AppId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ghichu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Viettat")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("is_Delete")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AppId");

                    b.ToTable("DmFeature");

                    b.HasData(
                        new
                        {
                            Id = new Guid("dde7744a-c33f-4b37-a89a-b99fa576fc5c"),
                            AppId = new Guid("e680169e-7c1c-4be3-8158-4146ddc1c587"),
                            Ten = "Capbac",
                            is_Delete = false
                        },
                        new
                        {
                            Id = new Guid("f527444e-9e28-4ea2-adce-c0c9c80a8531"),
                            AppId = new Guid("e680169e-7c1c-4be3-8158-4146ddc1c587"),
                            Ten = "Chucvu",
                            is_Delete = false
                        },
                        new
                        {
                            Id = new Guid("5267b5e2-ce19-465f-ad2d-9557e70aeeae"),
                            AppId = new Guid("e680169e-7c1c-4be3-8158-4146ddc1c587"),
                            Ten = "Donvi",
                            is_Delete = false
                        },
                        new
                        {
                            Id = new Guid("8b40b1e3-7e78-4fb4-9d7e-361a68e6a866"),
                            AppId = new Guid("e680169e-7c1c-4be3-8158-4146ddc1c587"),
                            Ten = "Canbo",
                            is_Delete = false
                        },
                        new
                        {
                            Id = new Guid("de976e05-5749-44c2-ba10-057e2aff7881"),
                            AppId = new Guid("c00464fc-ea88-428b-8904-25fa4afc07d5"),
                            Ten = "Dangkykenh",
                            is_Delete = false
                        },
                        new
                        {
                            Id = new Guid("b41759f2-2d93-419b-b527-095269951534"),
                            AppId = new Guid("c00464fc-ea88-428b-8904-25fa4afc07d5"),
                            Ten = "Dangkykenh_Duyet",
                            is_Delete = false
                        },
                        new
                        {
                            Id = new Guid("3e062997-8d32-454b-8f56-874ca6fc0b82"),
                            AppId = new Guid("c00464fc-ea88-428b-8904-25fa4afc07d5"),
                            Ten = "Soquanlykenh",
                            is_Delete = false
                        },
                        new
                        {
                            Id = new Guid("f42719ed-dd92-4c46-9ac3-c85ffd192c69"),
                            AppId = new Guid("3efbe184-cf3b-4afc-936c-bdf5f3784615"),
                            Ten = "Thongsohethong",
                            is_Delete = false
                        },
                        new
                        {
                            Id = new Guid("90937fa7-9ac9-44e6-8aad-1cb9f73aa4c7"),
                            AppId = new Guid("3efbe184-cf3b-4afc-936c-bdf5f3784615"),
                            Ten = "DmBlackWord",
                            is_Delete = false
                        });
                });

            modelBuilder.Entity("AMGAPI.Data.DmRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ghichu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("is_Delete")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("DmRole");

                    b.HasData(
                        new
                        {
                            Id = new Guid("830da2e4-c293-4026-b2e6-29ad8c935def"),
                            Ghichu = "Quản trị hệ thống",
                            Ten = "Administrator",
                            is_Delete = false
                        },
                        new
                        {
                            Id = new Guid("dde7744a-c33f-4b37-a89a-b99fa576fc5c"),
                            Ghichu = "Người dùng hệ thống",
                            Ten = "User",
                            is_Delete = false
                        });
                });

            modelBuilder.Entity("AMGAPI.Data.DmRole_Feature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AllowAdd")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowDuyet")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowEdit")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowView")
                        .HasColumnType("bit");

                    b.Property<Guid>("FeatureId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("is_Delete")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("FeatureId");

                    b.HasIndex("RoleId");

                    b.ToTable("DmRole_Feature");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7a90068f-2c2d-4d44-8ccf-e04b88d5d51e"),
                            AllowAdd = true,
                            AllowDelete = true,
                            AllowDuyet = true,
                            AllowEdit = true,
                            AllowView = true,
                            FeatureId = new Guid("dde7744a-c33f-4b37-a89a-b99fa576fc5c"),
                            RoleId = new Guid("830da2e4-c293-4026-b2e6-29ad8c935def"),
                            is_Delete = false
                        },
                        new
                        {
                            Id = new Guid("93651816-67d0-4e0d-86a9-50d22899cb1d"),
                            AllowAdd = true,
                            AllowDelete = true,
                            AllowDuyet = true,
                            AllowEdit = true,
                            AllowView = true,
                            FeatureId = new Guid("f527444e-9e28-4ea2-adce-c0c9c80a8531"),
                            RoleId = new Guid("830da2e4-c293-4026-b2e6-29ad8c935def"),
                            is_Delete = false
                        },
                        new
                        {
                            Id = new Guid("8633caac-e41c-4c4c-9c4a-b1ed2e960bf8"),
                            AllowAdd = true,
                            AllowDelete = true,
                            AllowDuyet = true,
                            AllowEdit = true,
                            AllowView = true,
                            FeatureId = new Guid("5267b5e2-ce19-465f-ad2d-9557e70aeeae"),
                            RoleId = new Guid("830da2e4-c293-4026-b2e6-29ad8c935def"),
                            is_Delete = false
                        },
                        new
                        {
                            Id = new Guid("1f5cf7a4-b4ac-4620-9c3e-51644548151b"),
                            AllowAdd = true,
                            AllowDelete = true,
                            AllowDuyet = true,
                            AllowEdit = true,
                            AllowView = true,
                            FeatureId = new Guid("8b40b1e3-7e78-4fb4-9d7e-361a68e6a866"),
                            RoleId = new Guid("830da2e4-c293-4026-b2e6-29ad8c935def"),
                            is_Delete = false
                        },
                        new
                        {
                            Id = new Guid("b5b9fcc6-1bb8-4576-982b-530d3429861c"),
                            AllowAdd = true,
                            AllowDelete = true,
                            AllowDuyet = true,
                            AllowEdit = true,
                            AllowView = true,
                            FeatureId = new Guid("3e062997-8d32-454b-8f56-874ca6fc0b82"),
                            RoleId = new Guid("830da2e4-c293-4026-b2e6-29ad8c935def"),
                            is_Delete = false
                        },
                        new
                        {
                            Id = new Guid("cf82e238-aef6-4145-8674-73fa21be5c1d"),
                            AllowAdd = true,
                            AllowDelete = true,
                            AllowDuyet = true,
                            AllowEdit = true,
                            AllowView = true,
                            FeatureId = new Guid("f42719ed-dd92-4c46-9ac3-c85ffd192c69"),
                            RoleId = new Guid("830da2e4-c293-4026-b2e6-29ad8c935def"),
                            is_Delete = false
                        },
                        new
                        {
                            Id = new Guid("6e7cc4c4-a3c6-42cc-9772-2e83abdc18b3"),
                            AllowAdd = true,
                            AllowDelete = true,
                            AllowDuyet = true,
                            AllowEdit = true,
                            AllowView = true,
                            FeatureId = new Guid("90937fa7-9ac9-44e6-8aad-1cb9f73aa4c7"),
                            RoleId = new Guid("830da2e4-c293-4026-b2e6-29ad8c935def"),
                            is_Delete = false
                        },
                        new
                        {
                            Id = new Guid("9e87e047-2c57-4e40-8b69-ae478861f07a"),
                            AllowAdd = true,
                            AllowDelete = true,
                            AllowDuyet = true,
                            AllowEdit = true,
                            AllowView = true,
                            FeatureId = new Guid("b41759f2-2d93-419b-b527-095269951534"),
                            RoleId = new Guid("830da2e4-c293-4026-b2e6-29ad8c935def"),
                            is_Delete = false
                        },
                        new
                        {
                            Id = new Guid("17f71279-793d-4b2a-a12c-a9f4013bb779"),
                            AllowAdd = true,
                            AllowDelete = true,
                            AllowDuyet = true,
                            AllowEdit = true,
                            AllowView = true,
                            FeatureId = new Guid("de976e05-5749-44c2-ba10-057e2aff7881"),
                            RoleId = new Guid("830da2e4-c293-4026-b2e6-29ad8c935def"),
                            is_Delete = false
                        });
                });

            modelBuilder.Entity("AMGAPI.Data.DmThongbao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Ngaytao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Noidungtinnhan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sodienthoaigui")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Sodienthoainhan")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<Guid>("SoquanlykenhId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Tieudetinnhan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Trangthai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("SoquanlykenhId");

                    b.ToTable("DmThongbao");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b079a0b9-50b1-4e54-af26-96f1e6576926"),
                            Ngaytao = new DateTime(2022, 10, 14, 0, 36, 56, 149, DateTimeKind.Utc).AddTicks(9864),
                            Noidungtinnhan = "CĐ-ĐH",
                            Sodienthoainhan = "0395248002",
                            SoquanlykenhId = new Guid("565b84a8-792f-4bcc-a701-1c7aae1930f0"),
                            Trangthai = false
                        },
                        new
                        {
                            Id = new Guid("9b773e21-4ee4-4e50-adc7-1edb42dbcfb1"),
                            Ngaytao = new DateTime(2022, 10, 14, 0, 36, 56, 150, DateTimeKind.Utc).AddTicks(263),
                            Noidungtinnhan = "CĐN",
                            Sodienthoainhan = "0395248002",
                            SoquanlykenhId = new Guid("565b84a8-792f-4bcc-a701-1c7aae1930f0"),
                            Trangthai = false
                        });
                });

            modelBuilder.Entity("AMGAPI.Data.DmThongbao_File", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("File_Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("IdThongbao")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenFile")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("ThongbaoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ThongbaoId");

                    b.ToTable("DmThongbao_File");
                });

            modelBuilder.Entity("AMGAPI.Data.DmUngdung", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ghichu")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Viettat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("is_Delete")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("DmUngdung");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5f606928-41d0-4b2d-a251-56ed76e1dffd"),
                            Ghichu = "CĐ-ĐH",
                            Ten = "Hệ thông tin CĐ-ĐH",
                            Viettat = "CĐ-ĐH",
                            is_Delete = false
                        },
                        new
                        {
                            Id = new Guid("16a5a7df-3f2c-49d9-b5ee-024e2487d7e1"),
                            Ghichu = "CĐN",
                            Ten = "Chỉ đạo ngành",
                            Viettat = "CĐN",
                            is_Delete = false
                        },
                        new
                        {
                            Id = new Guid("538a0883-c18d-40c8-ac53-70a3cc32215b"),
                            Ghichu = "QLVB",
                            Ten = "Quản lý văn bản",
                            Viettat = "QLVB",
                            is_Delete = false
                        });
                });

            modelBuilder.Entity("AMGAPI.Data.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExpiredAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("JwtId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshToken");
                });

            modelBuilder.Entity("AMGAPI.Data.Soquanlykenh", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CanboId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Dangkykenh_DuyetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IP_Internalgate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("IP_Ungdung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdDonvi")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Log_process")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayHuyKichHoat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKichHoat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Ngaysua")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<DateTime>("Ngaytao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<DateTime>("Ngayvaoso")
                        .HasColumnType("datetime2");

                    b.Property<int>("Port_Internalgate")
                        .HasColumnType("int");

                    b.Property<int>("Port_Ungdung")
                        .HasColumnType("int");

                    b.Property<string>("TenUngdung")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Ten_Kihieukenh")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Trangthai")
                        .HasColumnType("int");

                    b.Property<Guid>("UngdungId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("is_Delete")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Dangkykenh_DuyetId");

                    b.HasIndex("Ten_Kihieukenh")
                        .IsUnique()
                        .HasFilter("[Ten_Kihieukenh] IS NOT NULL");

                    b.HasIndex("UngdungId");

                    b.ToTable("Soquanlykenh");

                    b.HasData(
                        new
                        {
                            Id = new Guid("565b84a8-792f-4bcc-a701-1c7aae1930f0"),
                            CanboId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Dangkykenh_DuyetId = new Guid("6746de28-4d95-4a77-96de-c75a8eb80bc4"),
                            IP_Internalgate = "10.10.10.0",
                            IP_Ungdung = "10.10.10.1",
                            IdDonvi = new Guid("574b452c-b586-499b-d7b9-08da44749b96"),
                            NgayHuyKichHoat = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayKichHoat = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Ngaysua = new DateTime(2022, 10, 14, 0, 36, 56, 150, DateTimeKind.Utc).AddTicks(2900),
                            Ngaytao = new DateTime(2022, 10, 14, 0, 36, 56, 150, DateTimeKind.Utc).AddTicks(2675),
                            Ngayvaoso = new DateTime(2022, 10, 14, 0, 36, 56, 150, DateTimeKind.Utc).AddTicks(3121),
                            Port_Internalgate = 80,
                            Port_Ungdung = 80,
                            TenUngdung = "CĐ-ĐH",
                            Ten_Kihieukenh = "CDDH",
                            Trangthai = 0,
                            UngdungId = new Guid("5f606928-41d0-4b2d-a251-56ed76e1dffd"),
                            is_Delete = false
                        },
                        new
                        {
                            Id = new Guid("46988f74-1475-4283-a128-dda4f4b16094"),
                            CanboId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Dangkykenh_DuyetId = new Guid("97c3636d-cff0-4b80-b426-dc299e373053"),
                            IP_Internalgate = "10.10.10.0",
                            IP_Ungdung = "10.10.10.2",
                            IdDonvi = new Guid("574b452c-b586-499b-d7b9-08da44749b96"),
                            NgayHuyKichHoat = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayKichHoat = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Ngaysua = new DateTime(2022, 10, 14, 0, 36, 56, 150, DateTimeKind.Utc).AddTicks(3754),
                            Ngaytao = new DateTime(2022, 10, 14, 0, 36, 56, 150, DateTimeKind.Utc).AddTicks(3752),
                            Ngayvaoso = new DateTime(2022, 10, 14, 0, 36, 56, 150, DateTimeKind.Utc).AddTicks(3754),
                            Port_Internalgate = 80,
                            Port_Ungdung = 80,
                            TenUngdung = "CĐN",
                            Ten_Kihieukenh = "CDN",
                            Trangthai = 0,
                            UngdungId = new Guid("16a5a7df-3f2c-49d9-b5ee-024e2487d7e1"),
                            is_Delete = false
                        });
                });

            modelBuilder.Entity("AMGAPI.Data.ThongsoHethong", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("Datadiode_IP")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Datadiode_Port")
                        .HasColumnType("int");

                    b.Property<string>("Datadiode_Token")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<double>("KichthuocFilesMax")
                        .HasColumnType("float");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<double>("TanSuatXoanhatky_ngay")
                        .HasColumnType("float");

                    b.Property<int>("TansuatQuet_Phut")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ThongsoHethong");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9645cf84-11af-485f-8b90-fd34f3d7f26a"),
                            CreateDate = new DateTime(2022, 10, 14, 0, 36, 56, 152, DateTimeKind.Utc).AddTicks(2411),
                            Datadiode_IP = "1.1.1.1",
                            Datadiode_Port = 5033,
                            Datadiode_Token = "123",
                            KichthuocFilesMax = 1.0,
                            ModifiedDate = new DateTime(2022, 10, 14, 0, 36, 56, 152, DateTimeKind.Utc).AddTicks(2642),
                            TanSuatXoanhatky_ngay = 1.0,
                            TansuatQuet_Phut = 10
                        });
                });

            modelBuilder.Entity("AMGAPI.Data.Canbo", b =>
                {
                    b.HasOne("AMGAPI.Data.DmCapbac", "Capbac")
                        .WithMany("Canbos")
                        .HasForeignKey("CapbacId")
                        .HasConstraintName("FK_Canbo_Capbac")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AMGAPI.Data.DmChucvu", "Chucvu")
                        .WithMany("Canbos")
                        .HasForeignKey("ChucvuId")
                        .HasConstraintName("FK_Canbo_Chucvu")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AMGAPI.Data.DmDonvi", "Donvi")
                        .WithMany("Canbos")
                        .HasForeignKey("DonviId")
                        .HasConstraintName("FK_Canbo_Donvi")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AMGAPI.Data.DmRole", "Role")
                        .WithMany("Canbos")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("FK_Canbo_Role")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Capbac");

                    b.Navigation("Chucvu");

                    b.Navigation("Donvi");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("AMGAPI.Data.Dangkykenh", b =>
                {
                    b.HasOne("AMGAPI.Data.Canbo", "CanboDangky")
                        .WithMany()
                        .HasForeignKey("CanboDangkyId");

                    b.HasOne("AMGAPI.Data.DmUngdung", "Ungdung")
                        .WithMany("Dangkykenhs")
                        .HasForeignKey("UngdungId")
                        .HasConstraintName("FK_Dangkykenh_Ungdung")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CanboDangky");

                    b.Navigation("Ungdung");
                });

            modelBuilder.Entity("AMGAPI.Data.Dangkykenh_Duyet", b =>
                {
                    b.HasOne("AMGAPI.Data.Dangkykenh", "Dangkykenh")
                        .WithMany()
                        .HasForeignKey("DangkykenhId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AMGAPI.Data.Canbo", "CanboDuyet")
                        .WithMany()
                        .HasForeignKey("ID_Canboduyet");

                    b.HasOne("AMGAPI.Data.DmUngdung", "Ungdung")
                        .WithMany("Dangkykenh_Duyets")
                        .HasForeignKey("UngdungId")
                        .HasConstraintName("FK_DKDuyet_Ungdung")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CanboDuyet");

                    b.Navigation("Dangkykenh");

                    b.Navigation("Ungdung");
                });

            modelBuilder.Entity("AMGAPI.Data.Danhsachnguoidung", b =>
                {
                    b.HasOne("AMGAPI.Data.Canbo", "Canbo")
                        .WithMany()
                        .HasForeignKey("CanboId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AMGAPI.Data.Soquanlykenh", "Sokenh")
                        .WithMany()
                        .HasForeignKey("SokenhId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Canbo");

                    b.Navigation("Sokenh");
                });

            modelBuilder.Entity("AMGAPI.Data.DmDonvi", b =>
                {
                    b.HasOne("AMGAPI.Data.Dangkykenh", "Dangkykenh")
                        .WithMany()
                        .HasForeignKey("DangkykenhId");

                    b.HasOne("AMGAPI.Data.Dangkykenh_Duyet", "Dangkykenh_duyet")
                        .WithMany()
                        .HasForeignKey("Dangkykenh_duyetId");

                    b.HasOne("AMGAPI.Data.Soquanlykenh", "Soquanlykenh")
                        .WithMany()
                        .HasForeignKey("SoquanlykenhId");

                    b.Navigation("Dangkykenh");

                    b.Navigation("Dangkykenh_duyet");

                    b.Navigation("Soquanlykenh");
                });

            modelBuilder.Entity("AMGAPI.Data.DmFeature", b =>
                {
                    b.HasOne("AMGAPI.Data.DmApp", "App")
                        .WithMany("Features")
                        .HasForeignKey("AppId")
                        .HasConstraintName("FK_Feature_App")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("App");
                });

            modelBuilder.Entity("AMGAPI.Data.DmRole_Feature", b =>
                {
                    b.HasOne("AMGAPI.Data.DmFeature", "Feature")
                        .WithMany()
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AMGAPI.Data.DmRole", "Role")
                        .WithMany("Role_Features")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("FK_RoleFeature_Role")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Feature");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("AMGAPI.Data.DmThongbao", b =>
                {
                    b.HasOne("AMGAPI.Data.Soquanlykenh", "Soquanlykenh")
                        .WithMany("Thongbaos")
                        .HasForeignKey("SoquanlykenhId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Soquanlykenh");
                });

            modelBuilder.Entity("AMGAPI.Data.DmThongbao_File", b =>
                {
                    b.HasOne("AMGAPI.Data.DmThongbao", "Thongbao")
                        .WithMany()
                        .HasForeignKey("ThongbaoId");

                    b.Navigation("Thongbao");
                });

            modelBuilder.Entity("AMGAPI.Data.RefreshToken", b =>
                {
                    b.HasOne("AMGAPI.Data.Canbo", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("AMGAPI.Data.Soquanlykenh", b =>
                {
                    b.HasOne("AMGAPI.Data.Dangkykenh_Duyet", "Dangkykenh_Duyet")
                        .WithMany()
                        .HasForeignKey("Dangkykenh_DuyetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AMGAPI.Data.DmUngdung", "Ungdung")
                        .WithMany("Soquanlykenhs")
                        .HasForeignKey("UngdungId")
                        .HasConstraintName("FK_SoQLKenh_Ungdung")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Dangkykenh_Duyet");

                    b.Navigation("Ungdung");
                });

            modelBuilder.Entity("AMGAPI.Data.DmApp", b =>
                {
                    b.Navigation("Features");
                });

            modelBuilder.Entity("AMGAPI.Data.DmCapbac", b =>
                {
                    b.Navigation("Canbos");
                });

            modelBuilder.Entity("AMGAPI.Data.DmChucvu", b =>
                {
                    b.Navigation("Canbos");
                });

            modelBuilder.Entity("AMGAPI.Data.DmDonvi", b =>
                {
                    b.Navigation("Canbos");
                });

            modelBuilder.Entity("AMGAPI.Data.DmRole", b =>
                {
                    b.Navigation("Canbos");

                    b.Navigation("Role_Features");
                });

            modelBuilder.Entity("AMGAPI.Data.DmUngdung", b =>
                {
                    b.Navigation("Dangkykenh_Duyets");

                    b.Navigation("Dangkykenhs");

                    b.Navigation("Soquanlykenhs");
                });

            modelBuilder.Entity("AMGAPI.Data.Soquanlykenh", b =>
                {
                    b.Navigation("Thongbaos");
                });
#pragma warning restore 612, 618
        }
    }
}
